// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package database

import (
	"context"
	"uuid"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
    id,
    created_at
) VALUES (
    gen_random_uuid(),
    NOW()
)
RETURNING id, created_at
`

func (q *Queries) CreateChat(ctx context.Context) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat)
	var i Chat
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats
WHERE id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChat, id)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, created_at FROM chats
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getChatByTwoUsers = `-- name: GetChatByTwoUsers :one
SELECT chats.id FROM chats
JOIN chat_members cm1 ON cm1.chat_id = chats.id AND cm1.user_id = $1
JOIN chat_members cm2 ON cm2.chat_id = chats.id AND cm2.user_id = $2
`

type GetChatByTwoUsersParams struct {
	UserID   uuid.UUID
	UserID_2 uuid.UUID
}

func (q *Queries) GetChatByTwoUsers(ctx context.Context, arg GetChatByTwoUsersParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getChatByTwoUsers, arg.UserID, arg.UserID_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
