// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_members.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChatMember = `-- name: CreateChatMember :one
INSERT INTO chat_members (
    chat_id,
    user_id
) VALUES (
    $1,
    $2
)
RETURNING chat_id, user_id
`

type CreateChatMemberParams struct {
	ChatID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CreateChatMember(ctx context.Context, arg CreateChatMemberParams) (ChatMember, error) {
	row := q.db.QueryRowContext(ctx, createChatMember, arg.ChatID, arg.UserID)
	var i ChatMember
	err := row.Scan(&i.ChatID, &i.UserID)
	return i, err
}

const getChatMember = `-- name: GetChatMember :one
SELECT chat_id, user_id FROM chat_members
WHERE chat_id = $1 AND user_id = $2
`

type GetChatMemberParams struct {
	ChatID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetChatMember(ctx context.Context, arg GetChatMemberParams) (ChatMember, error) {
	row := q.db.QueryRowContext(ctx, getChatMember, arg.ChatID, arg.UserID)
	var i ChatMember
	err := row.Scan(&i.ChatID, &i.UserID)
	return i, err
}
