// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friends
SET request_status = 'accepted'
WHERE user_id = $1 AND friend_id = $2
`

type AcceptFriendRequestParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, acceptFriendRequest, arg.UserID, arg.FriendID)
	return err
}

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friends (
    user_id,
    friend_id
) VALUES (
    $1,
    $2
)
RETURNING user_id, friend_id, request_status
`

type CreateFriendRequestParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, createFriendRequest, arg.UserID, arg.FriendID)
	var i Friend
	err := row.Scan(&i.UserID, &i.FriendID, &i.RequestStatus)
	return i, err
}

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friends (
    user_id, 
    friend_id, 
    request_status
) VALUES (
    $1, 
    $2, 
    'accepted'
)
`

type CreateFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, createFriendship, arg.UserID, arg.FriendID)
	return err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM friends
WHERE user_id = $1 AND friend_id = $2
`

type DeleteFriendRequestParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) DeleteFriendRequest(ctx context.Context, arg DeleteFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequest, arg.UserID, arg.FriendID)
	return err
}

const getFriendshipStatus = `-- name: GetFriendshipStatus :one
SELECT user_id, request_status FROM friends
WHERE (user_id = $1 AND friend_id = $2)
    OR (user_id = $2 AND friend_id = $1)
LIMIT 1
`

type GetFriendshipStatusParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

type GetFriendshipStatusRow struct {
	UserID        uuid.UUID
	RequestStatus string
}

func (q *Queries) GetFriendshipStatus(ctx context.Context, arg GetFriendshipStatusParams) (GetFriendshipStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getFriendshipStatus, arg.UserID, arg.FriendID)
	var i GetFriendshipStatusRow
	err := row.Scan(&i.UserID, &i.RequestStatus)
	return i, err
}
