// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friends
SET request_status = 'accepted'
WHERE user_id = $1 AND friend_id = $2
`

type AcceptFriendRequestParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, acceptFriendRequest, arg.UserID, arg.FriendID)
	return err
}

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friends (
    user_id,
    friend_id
) VALUES (
    $1,
    $2
)
RETURNING user_id, friend_id, request_status
`

type CreateFriendRequestParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, createFriendRequest, arg.UserID, arg.FriendID)
	var i Friend
	err := row.Scan(&i.UserID, &i.FriendID, &i.RequestStatus)
	return i, err
}

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friends (
    user_id, 
    friend_id, 
    request_status
) VALUES (
    $1, 
    $2, 
    'accepted'
)
`

type CreateFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, createFriendship, arg.UserID, arg.FriendID)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friends
WHERE (user_id = $1 AND friend_id = $2)
   OR (user_id = $2 AND friend_id = $1)
`

type DeleteFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const getAllFriendsForUser = `-- name: GetAllFriendsForUser :many
Select friend.id AS friend_id, friend.nickname AS friend_nickname
FROM friends
JOIN users AS friend ON friend.id = friends.friend_id
WHERE friends.user_id = $1 AND friends.request_status = 'accepted'
`

type GetAllFriendsForUserRow struct {
	FriendID       uuid.UUID
	FriendNickname string
}

func (q *Queries) GetAllFriendsForUser(ctx context.Context, userID uuid.UUID) ([]GetAllFriendsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFriendsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFriendsForUserRow
	for rows.Next() {
		var i GetAllFriendsForUserRow
		if err := rows.Scan(&i.FriendID, &i.FriendNickname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendRequestsForUser = `-- name: GetFriendRequestsForUser :many
SELECT sender.nickname AS sender_nickname,
    receiver.nickname AS receiver_nickname
FROM friends
JOIN users AS sender ON sender.id = friends.user_id
JOIN users AS receiver ON receiver.id = friends.friend_id
WHERE (friends.user_id = $1 OR friends.friend_id = $1)
AND friends.request_status = 'pending'
`

type GetFriendRequestsForUserRow struct {
	SenderNickname   string
	ReceiverNickname string
}

func (q *Queries) GetFriendRequestsForUser(ctx context.Context, userID uuid.UUID) ([]GetFriendRequestsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendRequestsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendRequestsForUserRow
	for rows.Next() {
		var i GetFriendRequestsForUserRow
		if err := rows.Scan(&i.SenderNickname, &i.ReceiverNickname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendshipStatus = `-- name: GetFriendshipStatus :one
SELECT user_id, request_status FROM friends
WHERE (user_id = $1 AND friend_id = $2)
    OR (user_id = $2 AND friend_id = $1)
LIMIT 1
`

type GetFriendshipStatusParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

type GetFriendshipStatusRow struct {
	UserID        uuid.UUID
	RequestStatus string
}

func (q *Queries) GetFriendshipStatus(ctx context.Context, arg GetFriendshipStatusParams) (GetFriendshipStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getFriendshipStatus, arg.UserID, arg.FriendID)
	var i GetFriendshipStatusRow
	err := row.Scan(&i.UserID, &i.RequestStatus)
	return i, err
}
