// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    chat_id,
    sender_id,
    content,
    created_at
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW()
)
RETURNING id, chat_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ChatID   uuid.UUID
	SenderID uuid.UUID
	Content  string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesByChat = `-- name: GetMessagesByChat :many
SELECT messages.content, users.nickname, messages.created_at 
FROM messages
JOIN users ON users.id = messages.sender_id
WHERE messages.chat_id = $1
ORDER BY messages.created_at
LIMIT $2
`

type GetMessagesByChatParams struct {
	ChatID uuid.UUID
	Limit  int32
}

type GetMessagesByChatRow struct {
	Content   string
	Nickname  string
	CreatedAt time.Time
}

func (q *Queries) GetMessagesByChat(ctx context.Context, arg GetMessagesByChatParams) ([]GetMessagesByChatRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChat, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByChatRow
	for rows.Next() {
		var i GetMessagesByChatRow
		if err := rows.Scan(&i.Content, &i.Nickname, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
