// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    chat_id,
    sender_id,
    content,
    created_at
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW()
)
RETURNING id, chat_id, sender_id, content, created_at, is_read
`

type CreateMessageParams struct {
	ChatID   uuid.UUID
	SenderID uuid.UUID
	Content  string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.IsRead,
	)
	return i, err
}

const getMessagesByChat = `-- name: GetMessagesByChat :many
SELECT messages.content, users.nickname, messages.created_at 
FROM messages
JOIN users ON users.id = messages.sender_id
WHERE messages.chat_id = $1
ORDER BY messages.created_at
LIMIT $2
`

type GetMessagesByChatParams struct {
	ChatID uuid.UUID
	Limit  int32
}

type GetMessagesByChatRow struct {
	Content   string
	Nickname  string
	CreatedAt time.Time
}

func (q *Queries) GetMessagesByChat(ctx context.Context, arg GetMessagesByChatParams) ([]GetMessagesByChatRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChat, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByChatRow
	for rows.Next() {
		var i GetMessagesByChatRow
		if err := rows.Scan(&i.Content, &i.Nickname, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadMessages = `-- name: GetUnreadMessages :many
SELECT users.nickname, COUNT(*) as count
FROM messages
JOIN chats ON chats.id = messages.chat_id
JOIN chat_members ON chat_members.chat_id = chats.id AND chat_members.user_id = $1
JOIN users ON users.id = messages.sender_id
WHERE messages.is_read = FALSE AND messages.sender_id != $1
GROUP BY users.nickname
`

type GetUnreadMessagesRow struct {
	Nickname string
	Count    int64
}

func (q *Queries) GetUnreadMessages(ctx context.Context, userID uuid.UUID) ([]GetUnreadMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadMessagesRow
	for rows.Next() {
		var i GetUnreadMessagesRow
		if err := rows.Scan(&i.Nickname, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE messages
SET is_read = TRUE
WHERE chat_id = $1 AND sender_id != $2 AND is_read = FALSE
`

type MarkMessagesAsReadParams struct {
	ChatID   uuid.UUID
	SenderID uuid.UUID
}

func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markMessagesAsRead, arg.ChatID, arg.SenderID)
	return err
}
