// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

type ChatMember struct {
	ChatID uuid.UUID
	UserID uuid.UUID
}

type Message struct {
	ID        uuid.UUID
	ChatID    uuid.UUID
	SenderID  uuid.UUID
	Content   string
	CreatedAt time.Time
	IsRead    bool
}

type User struct {
	ID             uuid.UUID
	Nickname       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
